[package]
description = "Conflux state storage types"
homepage = "https://www.confluxnetwork.org"
license = "GPL-3.0"
name = "cfx-storage-types"
version = "1.0.0"
edition = "2021"

[dependencies]
cfx-db-errors = { workspace = true }
cfx-internal-common = { workspace = true }
cfx-types = { workspace = true }
primitives = { workspace = true }
rlp = { workspace = true }
